### ISSUE TITLE
race when starting

### ISSUE THREAD

**Issue by TomasTomecek** [TomasTomecek/sen#109]
with 1.12

```
Traceback (most recent call last):
  File "/usr/lib64/python3.5/threading.py", line 914, in _bootstrap_inner
    self.run()
  File "/usr/lib64/python3.5/threading.py", line 862, in run
    self._target(*self._args, **self._kwargs)
  File "/home/tt/g/sen/sen/tui/init.py", line 53, in realtime_updates
    self.ui.current_buffer.process_realtime_event(event)
AttributeError: 'NoneType' object has no attribute 'process_realtime_event'
```

**Comment by TomasTomecek** [comment]
This is already fixed; processing events is now guarded by try/exec block.
