### ISSUE TITLE
404 when getting RT event

### ISSUE THREAD

**Issue by TomasTomecek** [TomasTomecek/sen#110]
```
Traceback (most recent call last):
  File "/usr/lib64/python3.5/threading.py", line 914, in _bootstrap_inner
    self.run()
  File "/usr/lib64/python3.5/threading.py", line 862, in run
    self._target(*self._args, **self._kwargs)
  File "/home/tt/g/sen/sen/tui/init.py", line 53, in realtime_updates
    self.ui.current_buffer.process_realtime_event(event)
  File "/home/tt/g/sen/sen/tui/buffer.py", line 168, in process_realtime_event
    self.widget.refresh()
  File "/home/tt/g/sen/sen/tui/views/container_info.py", line 184, in refresh
    self.docker_container.refresh()
  File "/home/tt/g/sen/sen/docker_backend.py", line 239, in refresh
    self.inspect(cached=False)
  File "/home/tt/g/sen/sen/docker_backend.py", line 117, in wrapper
    response = func(self, *args, **kwargs)
  File "/home/tt/g/sen/sen/docker_backend.py", line 673, in inspect
    self._inspect = self.d.inspect_container(self.container_id)
  File "/usr/lib/python3.5/site-packages/docker/utils/decorators.py", line 21, in wrapped
    return f(self, resource_id, *args, **kwargs)
  File "/usr/lib/python3.5/site-packages/docker/api/container.py", line 182, in inspect_container
    self._get(self._url("/containers/{0}/json", container)), True
  File "/usr/lib/python3.5/site-packages/docker/client.py", line 178, in _result
    self._raise_for_status(response)
  File "/usr/lib/python3.5/site-packages/docker/client.py", line 173, in _raise_for_status
    raise errors.NotFound(e, response, explanation=explanation)
docker.errors.NotFound: 404 Client Error: Not Found ("b'{"message":"No such container: 7078e7013905113d40bbb56f2fd436020f16467f1c57df487ccd26b709811b4f"}'")
```

**Comment by TomasTomecek** [comment]
fixed by https://github.com/TomasTomecek/sen/commit/04b87021ed0c26cd8cbed22370eac74020e4d915
