### ISSUE TITLE
pip3 install seems return a lower version

### ISSUE THREAD

**Issue by wy193777** [TomasTomecek/sen#122]
Got exception when try to run 'sen'
```
Traceback (most recent call last):
  File "/usr/local/bin/sen", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.5/dist-packages/sen/cli.py", line 52, in main
    ui = Application()
  File "/usr/local/lib/python3.5/dist-packages/sen/tui/init.py", line 21, in __init__
    self.d = DockerBackend()
  File "/usr/local/lib/python3.5/dist-packages/sen/docker_backend.py", line 750, in __init__
    self.client = docker.AutoVersionClient(**kwargs)
AttributeError: module 'docker' has no attribute 'AutoVersionClient'
```
The code base has already applied this change, but pip3 installed still needs this class.

**Comment by TomasTomecek** [comment]
I'm sorry but I can't reproduce:

```
[root@07e7e5c8414f /]# pip3 install --user urwid
Collecting urwid
  Downloading urwid-1.3.1.tar.gz (588kB)
    100% |################################| 593kB 1.2MB/s
Installing collected packages: urwid
  Running setup.py install for urwid ... done
Successfully installed urwid

[root@07e7e5c8414f /]# pip3 install --user sen
Collecting sen
  Using cached sen-0.5.0-py3-none-any.whl
Requirement already satisfied (use --upgrade to upgrade): urwid in /root/.local/lib/python3.5/site-packages (from sen)
Collecting docker-py (from sen)
  Downloading docker_py-1.10.6-py2.py3-none-any.whl (50kB)
    100% |################################| 51kB 177kB/s
Collecting urwidtrees (from sen)
  Using cached urwidtrees-1.0.1.1.tar.gz
Collecting requests!=2.11.0,>=2.5.2 (from docker-py->sen)
  Downloading requests-2.13.0-py2.py3-none-any.whl (584kB)
    100% |################################| 593kB 1.5MB/s
Collecting websocket-client>=0.32.0 (from docker-py->sen)
  Downloading websocket_client-0.40.0.tar.gz (196kB)
    100% |################################| 204kB 1.9MB/s
Requirement already satisfied (use --upgrade to upgrade): six>=1.4.0 in /usr/lib/python3.5/site-packages (from docker-py->sen)
Collecting docker-pycreds>=0.2.1 (from docker-py->sen)
  Downloading docker_pycreds-0.2.1-py2.py3-none-any.whl
Installing collected packages: requests, websocket-client, docker-pycreds, docker-py, urwidtrees, sen
  Running setup.py install for websocket-client ... done
  Running setup.py install for urwidtrees ... done
Successfully installed docker-py-1.10.6 docker-pycreds-0.2.1 requests-2.13.0 sen-0.5.0 urwidtrees-1.0.1.1 websocket-client-0.40.0
```

This was done in a clean container.

What you are experiencing seems like you installed docker-py in version 2. `pip3 freeze | grep docker` would help me here. In such case, I might do a new release to support old and new version of docker-py.

**Comment by wy193777** [comment]
Install itself works fine, but throw exception when try to run sen.
`pip3 freeze | grep docker` output:
```
docker==2.0.1
docker-compose==1.10.0
docker-py==1.10.6
docker-pycreds==0.2.1
dockerpty==0.4.1
```

**Comment by TomasTomecek** [comment]
Wow, I don't understand how that's possible:

```
docker==2.0.1
docker-py==1.10.6
```

One of them has to be in your user's sitelib and the other one in global.

Will try to cut a new release this weekend, so sen works with `docker==2`. Thanks for report!

**Comment by TomasTomecek** [comment]
This is now released.
