### ISSUE TITLE
sen crashes on Debian Trixie with AttrSpecError in urwid (foreground/background color issue)

### ISSUE THREAD

**Issue by 0x6D682D7331** [TomasTomecek/sen#179]
Hello, 
I'm encountering a crash when running sen on Debian Trixie. The application fails to start and exits with a traceback. This seems to be related to urwid handling of colors, as seen in the `AttrSpecError`.

OS: Debian Trixie (testing)
Shell: zsh with oh-my-posh customization
Installed version: 0.7.0-2 (from Debian repositories)

Error Output: Below is the error traceback encountered during the crash:

```
Traceback (most recent call last):
  File "/usr/bin/sen", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/usr/lib/python3/dist-packages/sen/cli.py", line 63, in main
    app = Application(yolo=args.yolo)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/sen/tui/init.py", line 23, in __init__
    self.loop, self.ui = get_app_in_loop(PALLETE)
                         ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/sen/tui/ui.py", line 366, in get_app_in_loop
    screen.register_palette(pallete)
  File "/usr/lib/python3/dist-packages/urwid/display/common.py", line 1100, in register_palette
    self.register_palette_entry(*item)
  File "/usr/lib/python3/dist-packages/urwid/display/common.py", line 1181, in register_palette_entry
    mono_spec = AttrSpec(mono, DEFAULT, 1)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/urwid/display/common.py", line 598, in __init__
    raise AttrSpecError(
urwid.display.common.AttrSpecError: foreground/background ('white'/'default') require more colors than have been specified (1).
```

**Comment by TomasTomecek** [comment]
hi, thanks for the report!

indeed it seems that in the latest urwid release they changed color handling

i'll look into this in the coming days and cut a release with a fix

**Comment by TomasTomecek** [comment]
#180 fixes the root cause for me on my Fedora Linux 41, Python 3.13, urwid 2.6.14

please let me know if it works also on your Debian box, thanks!
