### ISSUE TITLE
urwid is not thread-safe: lock rendering

### ISSUE THREAD

**Issue by TomasTomecek** [TomasTomecek/sen#47]
```
11:25:22 sen                ERROR  Exception caught: AssertionError('rows, render mismatch',)
```

```
Traceback (most recent call last):
  File "/usr/lib64/python3.5/site-packages/urwid/main_loop.py", line 277, in run
    self._run()
  File "/usr/lib64/python3.5/site-packages/urwid/main_loop.py", line 374, in _run
    self.event_loop.run()
  File "/usr/lib64/python3.5/site-packages/urwid/main_loop.py", line 677, in run
    self._loop()
  File "/usr/lib64/python3.5/site-packages/urwid/main_loop.py", line 705, in _loop
    self._entering_idle()
  File "/usr/lib64/python3.5/site-packages/urwid/main_loop.py", line 666, in _entering_idle
    callback()
  File "/usr/lib64/python3.5/site-packages/urwid/main_loop.py", line 559, in entering_idle
    self.draw_screen()
  File "/usr/lib64/python3.5/site-packages/urwid/main_loop.py", line 573, in draw_screen
    canvas = self._topmost_widget.render(self.screen_size, focus=True)
  File "/usr/lib64/python3.5/site-packages/urwid/widget.py", line 140, in cached_render
    canv = fn(self, size, focus=focus)
  File "/usr/lib64/python3.5/site-packages/urwid/decoration.py", line 224, in render
    canv = self._original_widget.render(size, focus=focus)
  File "/usr/lib64/python3.5/site-packages/urwid/widget.py", line 140, in cached_render
    canv = fn(self, size, focus=focus)
  File "/usr/lib64/python3.5/site-packages/urwid/container.py", line 1095, in render
    assert foot.rows() == frows, "rows, render mismatch"
AssertionError: rows, render mismatch
```
When bulk-removing a lot of objects, this happens a lot. 

https://github.com/urwid/urwid/issues/165

**Comment by TomasTomecek** [comment]
After main listing rewrite this happens *a lot*. Definitely needs to be fixed before next release.
