### ISSUE TITLE
sen won't start on docker 1.8

### ISSUE THREAD

**Issue by TomasTomecek** [TomasTomecek/sen#55]
this is worth of doing a new release

```
Traceback (most recent call last):
  File "/home/ttomecek/dev/sen/sen/util.py", line 23, in wrapper
    response = func(*args, **kwargs)
  File "/home/ttomecek/dev/sen/sen/tui/init.py", line 151, in chain_fcs
    self.main_list_buffer.refresh(focus_on_top=True)
  File "/home/ttomecek/dev/sen/sen/tui/buffer.py", line 100, in refresh
    self.widget.populate(focus_on_top=focus_on_top)
  File "/home/ttomecek/dev/sen/sen/tui/widgets/list/main.py", line 145, in populate
    widgets = self._assemble_initial_content()
  File "/home/ttomecek/dev/sen/sen/tui/widgets/list/main.py", line 180, in _assemble_initial_content
    line = MainLineWidget(o)
  File "/home/ttomecek/dev/sen/sen/tui/widgets/list/main.py", line 87, in __init__
    image = AdHocAttrMap(urwid.Text(o.image_name()), get_map())
  File "/home/ttomecek/dev/sen/sen/docker_backend.py", line 464, in image_name
    image = self.docker_backend.get_image_by_id(self.image_id)
  File "/home/ttomecek/dev/sen/sen/docker_backend.py", line 458, in image_id
    image_id = self.data["ImageID"]
KeyError: 'ImageID'
```

**Comment by TomasTomecek** [comment]
please use development version of `sen`: `tomastomecek/sen:dev`; it's fixed there
