### ISSUE TITLE
sen from docker hub fails to run on engine 1.8

### ISSUE THREAD

**Issue by TomasTomecek** [TomasTomecek/sen#65]
```
08:02:25 sen.util           ERROR  Traceback (most recent call last):
  File "/usr/lib/python3.4/site-packages/sen/util.py", line 23, in wrapper
    response = func(*args, **kwargs)
  File "/usr/lib/python3.4/site-packages/sen/tui/init.py", line 151, in chain_fcs
    self.main_list_buffer.refresh(focus_on_top=True)
  File "/usr/lib/python3.4/site-packages/sen/tui/buffer.py", line 100, in refresh
    self.widget.populate(focus_on_top=focus_on_top)
  File "/usr/lib/python3.4/site-packages/sen/tui/widgets/list/main.py", line 145, in populate
    widgets = self._assemble_initial_content()
  File "/usr/lib/python3.4/site-packages/sen/tui/widgets/list/main.py", line 180, in _assemble_initial_content
    line = MainLineWidget(o)
  File "/usr/lib/python3.4/site-packages/sen/tui/widgets/list/main.py", line 87, in __init__
    image = AdHocAttrMap(urwid.Text(o.image_name()), get_map())
  File "/usr/lib/python3.4/site-packages/sen/docker_backend.py", line 463, in image_name
    image = self.docker_backend.get_image_by_id(self.image_id)
  File "/usr/lib/python3.4/site-packages/sen/docker_backend.py", line 457, in image_id
    image_id = self.data["ImageID"]
KeyError: 'ImageID'
```

**Comment by TomasTomecek** [comment]
dupe of #55 
 -,-
