### ISSUE TITLE
container info buffer: get network info gracefully

### ISSUE THREAD

**Issue by TomasTomecek** [TomasTomecek/sen#96]
```
Traceback (most recent call last):
  File "/home/tt/g/sen/sen/util.py", line 34, in wrapper
    response = func(*args, **kwargs)
  File "/home/tt/g/sen/sen/tui/commands/display.py", line 62, in run
    self.ui.add_and_display_buffer(buffer_class(self.docker_object, self.ui))
  File "/home/tt/g/sen/sen/tui/buffer.py", line 140, in __init__
    super().__init__()
  File "/home/tt/g/sen/sen/tui/buffer.py", line 56, in __init__
    self.refresh()
  File "/home/tt/g/sen/sen/tui/buffer.py", line 103, in refresh
    refresh_func()
  File "/home/tt/g/sen/sen/tui/widgets/info.py", line 283, in refresh
    self._net()
  File "/home/tt/g/sen/sen/tui/widgets/info.py", line 331, in _net
    ips = self.docker_container.net.ips
  File "/home/tt/g/sen/sen/net.py", line 74, in ips
    for network_name, network_data in self.inspect_data["NetworkSettings"]["Networks"].items():
AttributeError: 'NoneType' object has no attribute 'items'
```

container is created by k8s

**Comment by TomasTomecek** [comment]
More info:

```
  "NetworkSettings": {
    "SecondaryIPAddresses": null,
    "EndpointID": "",
    "IPv6Gateway": "",
    "IPAddress": "",
    "LinkLocalIPv6PrefixLen": 0,
    "Networks": null,
    "GlobalIPv6PrefixLen": 0,
    "MacAddress": "",
    "GlobalIPv6Address": "",
    "SandboxID": "",
    "SecondaryIPv6Addresses": null,
    "SandboxKey": "",
    "HairpinMode": false,
    "IPPrefixLen": 0,
    "Bridge": "",
    "Gateway": "",
    "Ports": null,
    "LinkLocalIPv6Address": ""
  },
```
